version: '3.9'

services:
  NovaScript:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./data/user.json:/app/data/user.json
      - ./data/chats:/app/data/chats
      - ./public/uploads:/app/public/uploads
    restart: unless-stopped