version: '3.9'

services:
  novascript:
    container_name: novascript
    image: davoola/novascript
    ports:
      - "8002:3000"
    environment:
      - NODE_ENV=production
      - TZ=Asia/Shanghai
    volumes:
      - ./data/users.json:/app/data/users.json
      - ./data/chats:/app/data/chats
      - ./data/uploads:/app/public/uploads
    restart: unless-stopped