version: '3.9'

services:
  novascript:
    container_name: novascript
    build: .
    image: davoola/novascript
    ports:
      - "8002:3000"
    environment:
      - NODE_ENV=production
      - TZ=Asia/Shanghai
    volumes:
      - ./data/users.json:/app/data/users.json
      - ./data/db:/app/data/db
      - ./public/uploads:/app/public/uploads
    restart: unless-stopped
    