version: '3.8'

services:
  novascript:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./data/users.json:/app/data/users.json
      - ./data/chats:/app/data/chats
      - ./public/uploads:/app/public/uploads
    restart: unless-stopped